actuators = {
    "SG90": {
        # "_id": {"$oid": "65dd0ff411bbe96dbfe4b2d6"},
        "type": "Actuador",
        "name": "Micro Servomotor",
        "brand": "TowerPro",
        "model": "SG90",
        "specifications": [
            {
                "name": "Velocidad de operación",
                "value": 0.12,
                "unit": "segundos/60°",
            },
            {"name": "Torque", "value": 2.5, "unit": "kg-cm"},
            {
                "name": "Voltage de operación",
                "value": 5.0,
                "unit": "V",
            },
            {
                "name": "Corriente de operación",
                "value": 10.0,
                "unit": "mA",
                "type": "VCD",
            },
            {
                "name": "Consumo eléctrico",
                "value": 0.5,
                "unit": "W",
            },
        ],
        "location": "",
        "status": "Disponible",
        "initialDate": 0,
        "owner": "MAHITECH-Haziel",
        "startsAt": 0,
        "endsAt": 0,
        "actions": [
            {
                "name": "Acticación mecánica",
                "value": "90",
                "unit": "°",
                "status": "Interrumpido",
            }
        ],
    },
    "FAN": {
        # "_id": {"$oid": "65d4f24c14a33a3563f3d1ee"},
        "type": "Actuador",
        "name": "Ventilador",
        "brand": "SY",
        "model": "DC BRUSHLESS FAN",
        "specifications": [
            {"name": "Tamaño", "value": 30.0, "unit": "mm"},
            {"name": "Peso", "value": 9.0, "unit": "g"},
            {"name": "Sonido", "value": 25.0, "unit": "dB"},
            {
                "name": "Velocidad de operación",
                "value": 8000.0,
                "unit": "rpm",
            },
            {
                "name": "Desplazamiento de aire",
                "value": 3.3,
                "unit": "cfm",
            },
            {
                "name": "Voltage de operación",
                "value": 5.0,
                "unit": "V",
            },
            {
                "name": "Corriente de operación",
                "value": 0.13,
                "unit": "A",
                "type": "VCD",
            },
            {
                "name": "Consumo eléctrico",
                "value": 1.56,
                "unit": "W",
            },
        ],
        "location": "",
        "status": "Disponible",
        "initialDate": 0,
        "owner": "MAHITECH-Haziel",
        "startsAt": 0,
        "endsAt": 0,
        "actions": [{"name": "Acticación mecánica", "value": "30", "unit": "%"}],
    },
    "SRD": {
            # "_id": {"$oid": "65dd0e5511bbe96dbfe4b2d5"},
            "type": "Actuador",
            "name": "Relevador",
            "brand": "Songle",
            "model": "SRD-05VDC-SLC",
            "specifications": [
                {
                    "name": "Interrupciones mecánicas",
                    "value": 300.0,
                    "unit": "operaciones/minuto",
                },
                {
                    "name": "Interrupciones eléctricas",
                    "value": 30.0,
                    "unit": "operaciones/minuto",
                },
                {
                    "name": "Voltage de operación",
                    "value": 5.0,
                    "unit": "V",
                },
                {"name": "Tipo de corriente", "value": "DC"},
                {
                    "name": "Corriente de operación",
                    "value": 10.0,
                    "unit": "mA",
                    "type": "VCD",
                },
                {
                    "name": "Consumo eléctrico",
                    "value": 0.25,
                    "unit": "W",
                },
            ],
            "location": "",
            "status": "Disponible",
            "initialDate": 0,
            "owner": "MAHITECH-Haziel",
            "startsAt": 0,
            "endsAt": 0,
            "actions": [{"name": "Acticación mecánica", "value": "Activado"}],
        }
}
